#!/bin/bash
apt-get update && apt-get install gcc g++ grub2 xorriso build-essential nasm

rm -rf cmake-3.9.4 && \
wget -nc http://www.cmake.org/files/v3.9/cmake-3.9.4.tar.gz && \
tar -xvzf cmake-3.9.4.tar.gz && \
cd cmake-3.9.4/ && \
./configure && make && make install && update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force && \
rm -f cmake-3.9.4.tar.gz && \
rm -rf cmake-3.9.4
