#!/bin/bash
apt-get install gcc g++ grub2 xorriso build-essential nasm

rm -rf cmake-3.8.1
wget -nc http://www.cmake.org/files/v3.8/cmake-3.8.1.tar.gz 
tar -xvzf cmake-3.8.1.tar.gz 
cd cmake-3.8.1/ 
./configure 
make 
make install
update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
